services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chronoquest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      otterverse-net:
        aliases:
          - chronoquest-backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      otterverse-net:
        aliases:
          - chronoquest-frontend

networks:
  otterverse-net:
    external: true

volumes:
  db_data:
