version: '3.8'

services:
  backend:
    build:
      context: .  # Use the root directory as the build context
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared  # Mount shared folder
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: .  # Use the root directory as the build context
      dockerfile: frontend/Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared  # Mount shared folder
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
